package jetsonserver;

import java.io.IOException;

public class main extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MoveButton2 = new javax.swing.JButton();
        HelpButton = new javax.swing.JButton();
        MoveButton1 = new javax.swing.JButton();
        MoveButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextBox1 = new javax.swing.JTextArea();
        ArduinoConnect = new javax.swing.JButton();
        ArduinoDisconnect = new javax.swing.JButton();
        Label1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MoveButton2.setText("Y: +500");
        MoveButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoveButton2ActionPerformed(evt);
            }
        });

        HelpButton.setText("Help");
        HelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpButtonActionPerformed(evt);
            }
        });

        MoveButton1.setText("X: +100");
        MoveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoveButton1ActionPerformed(evt);
            }
        });

        MoveButton3.setText("X: -900");
        MoveButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoveButton3ActionPerformed(evt);
            }
        });

        TextBox1.setColumns(20);
        TextBox1.setRows(5);
        TextBox1.setText("This is the debug box. \n\nAll information will show up here.");
        jScrollPane1.setViewportView(TextBox1);

        ArduinoConnect.setText("Connect To Arduino");
        ArduinoConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArduinoConnectActionPerformed(evt);
            }
        });

        ArduinoDisconnect.setText("Disconnect From Arduino");
        ArduinoDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArduinoDisconnectActionPerformed(evt);
            }
        });

        Label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Label1.setForeground(new java.awt.Color(255, 255, 255));
        Label1.setText("Arduino Mega Motor Control Client");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(HelpButton, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 51, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Label1)
                                .addGap(51, 51, 51))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(ArduinoConnect)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ArduinoDisconnect)
                                .addGap(39, 39, 39))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MoveButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MoveButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MoveButton3)
                .addGap(94, 94, 94))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ArduinoConnect)
                    .addComponent(ArduinoDisconnect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MoveButton1)
                    .addComponent(MoveButton2)
                    .addComponent(MoveButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HelpButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void display(String x){
        TextBox1.setText(x);
    }
    
    private void MoveButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoveButton2ActionPerformed
        try{
            JetsonServer.send("y+500");
            display("Moved Y 500.");
        } catch (IOException e) {
            display("Could not send 'y+500' to Arduino.");
        }
    }//GEN-LAST:event_MoveButton2ActionPerformed

    private void HelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpButtonActionPerformed
        display("This is a User Interface designed to run on the NVidia Jetson. \n\nMake sure to have the Arduino Mega connected to the Jetson via\nEthernet. In addition, make sure the Ethernet Shield is connected and\nsecured to the Mega. \n\nThe buttons on the main interface currently work with only one motor\nconnected. For example, if you hit \"500\", the motor will move 500\nsteps. \n\nFurther development will be made by James.");
    }//GEN-LAST:event_HelpButtonActionPerformed

    private void MoveButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoveButton3ActionPerformed
        try{
            JetsonServer.send("x-900");
            display("Moved X -900.");
        } catch (IOException e) {
            display("Could not send 'x-900' to Arduino.");
        }
    }//GEN-LAST:event_MoveButton3ActionPerformed

    private void MoveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoveButton1ActionPerformed
        try{
            JetsonServer.send("x+100");
            display("Moved X 100.");
        } catch (IOException e) {
            display("Could not send 'x+100' to Arduino.");
        }
    }//GEN-LAST:event_MoveButton1ActionPerformed

    private void ArduinoConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArduinoConnectActionPerformed
        if (JetsonServer.connect() == false) {
            display("Failed to connect to Arduino Mega.");
        } else {
            display("Connected to Arduino Mega!");
        }
    }//GEN-LAST:event_ArduinoConnectActionPerformed

    private void ArduinoDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArduinoDisconnectActionPerformed
        if (JetsonServer.disconnect() == false) {
            display("Failed to disconnect from Arduino Mega.");
        } else {
            display("Disconnected from Arduino Mega!");
        }
    }//GEN-LAST:event_ArduinoDisconnectActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new main().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ArduinoConnect;
    private javax.swing.JButton ArduinoDisconnect;
    private javax.swing.JButton HelpButton;
    private javax.swing.JLabel Label1;
    private javax.swing.JButton MoveButton1;
    private javax.swing.JButton MoveButton2;
    private javax.swing.JButton MoveButton3;
    private javax.swing.JTextArea TextBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
